version: '3.8'

services:

   db:
     image: mariadb
     command: --max_allowed_packet=67108864
     volumes:
       - ./db_data:/var/lib/mysql:delegated
     restart: "no"
     ports:
       - "33012:3306"
     environment:
       MARIADB_ROOT_PASSWORD: bgriz_root
       MARIADB_DATABASE: bgriz_db
       MARIADB_USER: bgriz_user
       MARIADB_PASSWORD: bgriz_pass

   wordpress:
     depends_on:
       - db
     image: wordpress:latest
     volumes:
       - ./../bgriz-timber/:/var/www/html:delegated
       - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini:delegated
     ports:
       - "8012:80"
     restart: "no"
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: bgriz_user
       WORDPRESS_DB_PASSWORD: bgriz_pass
       WORDPRESS_DB_NAME: bgriz_db

volumes:
    db_data:
    uploads.ini:
